//
//  BasicConnectFlowPresenter.swift
//  Alysei
//
//  Created by Janu Gandhi on 11/06/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol BasicConnectFlowPresentationLogic {
    func showConnectionConfirmScreen()
    func showAlert(msg: String)
}

class BasicConnectFlowPresenter: BasicConnectFlowPresentationLogic {
    
    func showAlert(msg: String) {
        self.viewController?.alert(msg: msg)
    }
    
    weak var viewController: BasicConnectFlowDisplayLogic?
    
    
   
    func showConnectionConfirmScreen() {
            self.viewController?.showConnectionScreen()
    }
}
