//
//  EditPostModels.swift
//  Alysei
//
//  Created by Gitesh Dang on 29/09/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum EditPost
{
  // MARK: Use cases
        
        enum Edit {
            struct RequestModel: Codable {
                var privacyLabel: String
                var actionType: String
                var postID: Int
                var body: String?
                

                private enum CodingKeys: String, CodingKey {
                    case privacyLabel = "privacy"
                    case actionType = "action_type"
                    case postID = "shared_post_id"
                    case body = "body"
                }

            }
            struct Response {
            }
            struct ViewModel {
            }
        }

        enum EditData {
            struct edit {
                var attachments: [Attachments]?
                var postOwnerDetail: SubjectData?
                var postDescription: String?
                var postID: Int
                var privacy: String?
            }
        }
    }
