//
//  EditPostInteractor.swift
//  Alysei
//
//  Created by Gitesh Dang on 29/09/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol EditPostBusinessLogic
{
  //func doSomething(request: EditPost.Something.Request)
}

protocol EditPostDataStore
{
  //var name: String { get set }
}

class EditPostInteractor: EditPostBusinessLogic, EditPostDataStore
{
  var presenter: EditPostPresentationLogic?
  var worker: EditPostWorker?
  //var name: String = ""
  
  // MARK: Do something
  
//  func doSomething(request: EditPost.Something.Request)
//  {
//    worker = EditPostWorker()
//    worker?.doSomeWork()
//    
//    let response = EditPost.Something.Response()
//    presenter?.presentSomething(response: response)
//  }
}
