//
//  ChatConstants.swift
//  RippleApp
//
//  Created by Mohd Aslam on 30/04/20.
//  Copyright © 2020 Fluper. All rights reserved.
//

import Foundation

struct cellidentifiers {
    static let SendertextCell       = "SendertextCell"
    static let Receivertextcell     = "Receivertextcell"
    static let SenderImageCell      = "SenderImageCell"
    static let SenderTextImageCell      = "SenderTextImageCell"
    static let ReceiverImageCell    = "ReceiverImageCell"
    static let ReceiverTextImageCell    = "ReceiverTextImageCell"
    static let SenderVideoCell      = "SenderVideoCell"
    static let ReceiverVideoCell    = "ReceiverVideoCell"
    static let SenderPdfCell        = "SenderPdfCell"
    static let ReceiverPdfCell      = "ReceiverPdfCell"
    static let SenderLocationCell   = "SenderLocationCell"
    static let ReceiverLocationCell = "ReceiverLocationCell"
    static let SenderAudioCell      = "SenderAudioCell"
    static let ReceiverAudioCell    = "ReceiverAudioCell"
    
}

struct Parameters {
    
    static let mediaType                  = "mediaType"
    static let lastmessage                = "lastmessage"
    static let otherId                    = "otherId"
    static let otherImage                 = "otherImage"
    static let otherName                  = "otherName"
    static let readState                  = "readState"
    static let timestamp                  = "timestamp"
    static let uid                        = "uid"
    static let userTyping                 = "userTyping"
    static let readCount                 = "readCount"
    
    static let deleted                  = "deleted"
    static let like                  = "like"
    static let messages                  = "message"
    static let mediaImage                  = "mediaImage"
    static let receiverImage                 = "receiverImage"
    static let receiverName                 = "receiverName"
    static let receiverids                  = "receiverid"
    static let senderImage                 = "senderImage"
    static let senderName                 = "senderName"
    
    static let storeId                 = "storeId"
    static let storeName                 = "storeName"
    static let productId                 = "productId"
    static let productName                 = "productName"
    static let productImage                 = "productImage"
    static let producerUserId                 = "producerUserId"
    
    static let createdBy                  = "createdBy"
    static let UserSeenCount              = "UserSeenCount"
    static let CreatedBy                  = "group_id"
    static let Groups                     = "Groups"
    static let Message                    = "Messages"
    static let content                    = "message"
    static let videoName                  = "videoName"
    static let name                       = "name"
    static let senderid                   = "senderid"
    static let receiverid                 = "otherId"
    static let message                    = "Messages"
    static let post                    = "post"
    static let users                    = "users"
    static let commentLike                    = "comment_like"
    static let mediatype                  = "type"
    static let status                     = "status"
    static let img_type                   = "img_type"
    static let type                       = "type"
    static let mediaurl                   = "mediaurl"
    static let fileName                   = "fileName"
    static let unread_count               = "unread_count"
    static let groupName                  = "group_name"
    static let isDeleted                  = "deleted"
    static let thumnilimageurl            = "video_thumbnail"
    static let ResentMessage              = "RecentMessage"
    static let UserState                  = "Users"
    static let timeStamp                  = "timestamp"
    static let profile_image              = "profile_image"
    static let OnlineState                = "OnlineState"
    static let _id                        = "id"
    static let user_id                    = "_id"
    static let chat_id                    = "chat_id"
    static let alertmessage               = "Some Error node  not Found in Send data to firebase"
    static let Users                      = "members"
    static let information                = "information"
    static let emptyString                = ""
    static let saparaterString            = "_"
    static let nomessagesdata             = "No Data found"
    static let nobackupdata               = "No Backup Data found"
    static let blockUsers                 = "blockUsers"
    static let sendername                 = "sendername"
    static let location                   = "location"
    static let latitude                   = "latitude"
    static let longitude                  = "longitude"
    static let starmessage                = "starmessage"
    static let PrivateMessages            = "PrivateMessages"
    static let groupid                    = "group_id"
    static let  groupname                 = "group_name"
    static let admin_id                   = "admin_id"
    static let _friend                    = "_friend"
    static let likeStatus                 = "likestatus"
    static let anonymous_chat                = "anonymous_chat"
    
    
    static let commentCount = "commentCount"
    static let likeCount = "likeCount"
    static let postId = "postId"
    static let comment = "comment"
    
    static let alysei_approval = "alysei_approval"
    
    static let body = "body"
    static let core_comment_id = "core_comment_id"
    static let previous_comment_id = "previous_comment_id"
    static let created_at = "created_at"
    static let isLike = "isLike"
    static let comment_like_count = "comment_like_count"
    static let poster = "poster"
    
    static let attachment_type = "attachment_type"
    static let attachment_url = "attachment_url"
    //var created_at : String?
    static let id = "id"
    static let like_id = "like_id"
    static let updated_at = "updated_at"
    static let base_url = "base_url"
    
    static let avatar_id = "avatar_id"
    static let email = "email"
    static let username = "name"
    static let restaurant_name = "restaurant_name"
    static let first_name = "first_name"
    static let company_name = "company_name"
    static let role_id = "role_id"
    static let userid = "user_id"
    static let notification = "notification"
}
